import json
import logging

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

from backend.services.content_store import content_store

logger = logging.getLogger(__name__)
router = APIRouter()


@router.websocket("/ws/content/{session_id}")
async def content_websocket(websocket: WebSocket, session_id: str):
    """WebSocket endpoint for delivering encyclopedia page content.

    The frontend connects here to receive rich visual content (text + images)
    generated by the encyclopedia tool. Content is published via the
    content_store pub/sub when the ADK agent's tool completes.
    """
    await websocket.accept()
    queue = content_store.subscribe(session_id)
    logger.info(f"Content WebSocket connected for session: {session_id}")

    try:
        while True:
            # Wait for new encyclopedia content
            page_data = await queue.get()
            await websocket.send_text(json.dumps(page_data))
    except WebSocketDisconnect:
        logger.info(f"Content WebSocket disconnected for session: {session_id}")
    except Exception as e:
        logger.error(f"Content WebSocket error: {e}")
    finally:
        content_store.unsubscribe(session_id, queue)
